databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    plan: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
    postDeploy:
      - "bundle exec rails db:migrate"
      - "bundle exec rails runner 'Admin.create!(email: \"admin@example.com\", password: \"password\", password_confirmation: \"password\") unless Admin.exists?(email: \"admin@example.com\")'"
      - "bundle exec rails runner 'puts Admin.count'"
      - "bundle exec rails runner 'puts Admin.first.email if Admin.count > 0'"